const express = require('express');
const cors = require('cors');
const routes = express.Router();
require('dotenv').config();
const {createUser,getUsersNames,UpdateUser,UserLogin,verifyJwtToken,home} = require('../controllers/userConrollers');
// routes.post('/createusers',createUser);
routes.get('/users/names',getUsersNames);
routes.put('/users/:id',UpdateUser);
routes.post('/login',UserLogin);
routes.get('/jwt',verifyJwtToken);
routes.get('/home',verifyJwtToken,home);
module.exports = routes;
